/**
 * Settings — self-service account hub.
 *
 * Three sections (inline tabs styled with btn-secondary / active = btn-primary):
 *
 *   1. Profile  — large Avatar + first/last name form (PUT /users/{uuid}.json, since the
 *                 backend rejects the "me" alias on writes). Read-only username + role.
 *                 Avatar upload is intentionally omitted (no backend write endpoint exists).
 *   2. Security — TOTP MFA. On mount probes GET /mfa/setup/totp/start.json to learn
 *                 whether MFA is already configured. If not: fetch GET /mfa/setup/totp.json
 *                 to obtain the otpauth:// provisioning URI, render it as a client-side QR
 *                 (no external dependency) + a copyable secret string, then verify a 6-digit
 *                 code via POST /mfa/setup/totp.json to enable. If configured: show the
 *                 verified timestamp + a Disable control (DELETE /mfa/setup/totp.json).
 *                 Brute-force 429 surfaces a dedicated banner.
 *   3. Account  — read-only GET /settings.json key/value table + the unlocked GPG key
 *                 fingerprint (from KeyContext / localStorage) + a Logout button. Admins
 *                 also get an org-wide MFA toggle (GET/POST /mfa/settings.json).
 *
 * Every data view has loading / empty / error states. E2EE invariant: the GPG key
 * fingerprint is read from the in-memory KeyContext (never decrypted on the server).
 */
import {
    useCallback,
    useEffect,
    useMemo,
    useRef,
    useState,
    type CSSProperties,
    type FormEvent,
    type ReactNode,
} from 'react';
import {
    User as UserIcon,
    ShieldCheck,
    ShieldOff,
    Server,
    Copy,
    Check,
    Fingerprint,
    LogOut,
    KeyRound,
    AlertTriangle,
} from 'lucide-react';
import { logout } from '../auth';
import { useKey } from '../crypto/KeyContext';
import { getMe, updateOwnProfile, avatarUrl } from '../services/profile';
import {
    getTotpSetupState,
    startTotpSetup,
    enableTotp,
    disableTotp,
    getOrgMfaSettings,
    updateOrgMfaSettings,
} from '../services/mfa';
import { getServerSettings } from '../services/settings';
import type {
    MfaOrgSettings,
    MfaSetupState,
    ServerSettings,
    User,
} from '../types';
import { Avatar } from '../components/Avatar';
import { Badge } from '../components/Badge';
import { ConfirmDialog } from '../components/ConfirmDialog';
import { FullSpinner, Spinner } from '../components/Spinner';
import { useToast } from '../components/toastContext';

// ---------------------------------------------------------------------------
// Error helpers
// ---------------------------------------------------------------------------
interface ApiErrorLike {
    response?: { status?: number; data?: { header?: { message?: string } } };
    message?: string;
}

function asApiError(err: unknown): ApiErrorLike {
    return (err ?? {}) as ApiErrorLike;
}

function errMessage(err: unknown, fallback: string): string {
    const e = asApiError(err);
    return e.response?.data?.header?.message || e.message || fallback;
}

function httpStatus(err: unknown): number | undefined {
    return asApiError(err).response?.status;
}

// ---------------------------------------------------------------------------
// otpauth:// parsing
// ---------------------------------------------------------------------------

/** Pull the base32 `secret` and human-readable label out of an otpauth:// URI. */
function parseOtpauth(uri: string): {
    secret: string | null;
    issuer: string | null;
    label: string | null;
} {
    try {
        // otpauth://totp/Issuer:account?secret=...&issuer=...
        const u = new URL(uri);
        const secret = u.searchParams.get('secret');
        const issuer = u.searchParams.get('issuer');
        const label = decodeURIComponent(u.pathname.replace(/^\/+/, '')) || null;
        return { secret, issuer, label };
    } catch {
        return { secret: null, issuer: null, label: null };
    }
}

const errorBannerStyle: CSSProperties = {
    background: 'rgba(248, 81, 73, 0.1)',
    color: 'var(--danger-color)',
    border: '1px solid var(--danger-color)',
    borderRadius: 'var(--radius-md)',
    padding: '12px 16px',
    fontSize: '14px',
    display: 'flex',
    alignItems: 'flex-start',
    gap: '10px',
    lineHeight: 1.5,
};

function ErrorBanner({ children }: { children: ReactNode }) {
    return (
        <div style={errorBannerStyle}>
            <AlertTriangle size={18} style={{ flexShrink: 0, marginTop: 1 }} />
            <span>{children}</span>
        </div>
    );
}

/**
 * A dependency-free QR code generated by encoding the otpauth URI into a QR
 * matrix and drawing it on a <canvas> (byte mode, error correction level M,
 * versions 1..10). Falls back to a "scan unavailable" hint if the payload is
 * too large for the supported versions.
 */
function OtpauthQr({ data, size = 196 }: { data: string; size?: number }) {
    const canvasRef = useRef<HTMLCanvasElement | null>(null);

    // Compute the matrix during render so the failure state is derived, not set
    // synchronously inside the effect (which the lint rule forbids).
    const matrix = useMemo<boolean[][] | null>(() => {
        try {
            return buildQrMatrix(data);
        } catch {
            return null;
        }
    }, [data]);

    useEffect(() => {
        const canvas = canvasRef.current;
        if (!canvas || !matrix) return;
        const ctx = canvas.getContext('2d');
        if (!ctx) return;
        const n = matrix.length;
        const quiet = 4; // quiet-zone modules
        const total = n + quiet * 2;
        const scale = Math.max(1, Math.floor(size / total));
        const px = total * scale;
        canvas.width = px;
        canvas.height = px;
        // White background so the dark-theme page doesn't break scanning.
        ctx.fillStyle = '#ffffff';
        ctx.fillRect(0, 0, px, px);
        ctx.fillStyle = '#000000';
        for (let r = 0; r < n; r++) {
            for (let c = 0; c < n; c++) {
                if (matrix[r][c]) {
                    ctx.fillRect((c + quiet) * scale, (r + quiet) * scale, scale, scale);
                }
            }
        }
    }, [matrix, size]);

    if (!matrix) {
        return (
            <div
                style={{
                    width: size,
                    height: size,
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    textAlign: 'center',
                    background: 'rgba(255,255,255,0.04)',
                    border: '1px dashed var(--panel-border)',
                    borderRadius: 'var(--radius-md)',
                    color: 'var(--text-muted)',
                    fontSize: '12px',
                    padding: '12px',
                }}
            >
                QR unavailable — paste the setup key below into your authenticator.
            </div>
        );
    }

    return (
        <canvas
            ref={canvasRef}
            style={{ width: size, height: size, borderRadius: 'var(--radius-md)', background: '#fff' }}
            aria-label="TOTP provisioning QR code"
        />
    );
}

// ---------------------------------------------------------------------------
// A copyable inline text chip.
// ---------------------------------------------------------------------------
function CopyChip({ value, mono = true }: { value: string; mono?: boolean }) {
    const [copied, setCopied] = useState(false);
    const onCopy = async () => {
        try {
            await navigator.clipboard.writeText(value);
            setCopied(true);
            window.setTimeout(() => setCopied(false), 2000);
        } catch {
            /* clipboard unavailable */
        }
    };
    return (
        <div style={{ display: 'flex', gap: '8px', alignItems: 'stretch' }}>
            <input
                className="form-control"
                value={value}
                readOnly
                onFocus={(e) => e.currentTarget.select()}
                style={{
                    flex: 1,
                    fontFamily: mono ? "'SFMono-Regular', Consolas, Menlo, monospace" : undefined,
                    fontSize: '13px',
                }}
            />
            <button
                type="button"
                className="btn btn-secondary"
                style={{ padding: '0 14px' }}
                onClick={onCopy}
                aria-label="Copy"
                title="Copy"
            >
                {copied ? <Check size={16} color="var(--success-color)" /> : <Copy size={16} />}
            </button>
        </div>
    );
}

// ---------------------------------------------------------------------------
// Tabs
// ---------------------------------------------------------------------------
type Tab = 'profile' | 'security' | 'account';

const TABS: { id: Tab; label: string; icon: typeof UserIcon }[] = [
    { id: 'profile', label: 'Profile', icon: UserIcon },
    { id: 'security', label: 'Security', icon: ShieldCheck },
    { id: 'account', label: 'Account', icon: Server },
];

// ===========================================================================
// Page
// ===========================================================================
export default function Settings() {
    const [tab, setTab] = useState<Tab>('profile');

    const [me, setMe] = useState<User | null>(null);
    const [meLoading, setMeLoading] = useState(true);
    const [meError, setMeError] = useState<string | null>(null);

    const loadMe = useCallback(async () => {
        setMeLoading(true);
        setMeError(null);
        try {
            const user = await getMe();
            setMe(user);
        } catch (err: unknown) {
            setMeError(errMessage(err, 'Failed to load your account.'));
        } finally {
            setMeLoading(false);
        }
    }, []);

    useEffect(() => {
        void loadMe();
    }, [loadMe]);

    const isAdmin = me?.role?.name === 'admin';

    return (
        <div className="container animate-fade-in">
            <div style={{ marginBottom: '24px' }}>
                <h1 style={{ margin: 0, fontSize: '26px' }}>Settings</h1>
                <p style={{ color: 'var(--text-secondary)', margin: '6px 0 0' }}>
                    Manage your profile, two-factor authentication, and account.
                </p>
            </div>

            {/* Tab strip */}
            <div style={{ display: 'flex', gap: '8px', marginBottom: '20px', flexWrap: 'wrap' }}>
                {TABS.map(({ id, label, icon: Icon }) => (
                    <button
                        key={id}
                        type="button"
                        className={`btn ${tab === id ? 'btn-primary' : 'btn-secondary'}`}
                        onClick={() => setTab(id)}
                        style={{ padding: '8px 16px' }}
                    >
                        <Icon size={16} /> {label}
                    </button>
                ))}
            </div>

            {meLoading ? (
                <div className="glass-panel" style={{ padding: '48px 20px' }}>
                    <FullSpinner label="Loading your account..." />
                </div>
            ) : meError ? (
                <ErrorBanner>{meError}</ErrorBanner>
            ) : (
                <>
                    {tab === 'profile' && me && <ProfileTab me={me} onSaved={loadMe} />}
                    {tab === 'security' && <SecurityTab />}
                    {tab === 'account' && me && <AccountTab me={me} isAdmin={isAdmin} />}
                </>
            )}
        </div>
    );
}

// ===========================================================================
// Profile tab
// ===========================================================================
function ProfileTab({ me, onSaved }: { me: User; onSaved: () => void | Promise<void> }) {
    const toast = useToast();
    const [firstName, setFirstName] = useState(me.profile?.first_name ?? '');
    const [lastName, setLastName] = useState(me.profile?.last_name ?? '');
    const [saving, setSaving] = useState(false);
    const [error, setError] = useState<string | null>(null);

    const dirty =
        firstName !== (me.profile?.first_name ?? '') || lastName !== (me.profile?.last_name ?? '');

    const avatarSrc = avatarUrl(me, 'medium');

    const handleSave = async (e: FormEvent) => {
        e.preventDefault();
        if (!firstName.trim() || !lastName.trim()) {
            setError('First and last name are required.');
            return;
        }
        setSaving(true);
        setError(null);
        try {
            await updateOwnProfile({
                first_name: firstName.trim(),
                last_name: lastName.trim(),
            });
            toast.success('Profile updated.');
            await onSaved();
        } catch (err: unknown) {
            const msg = errMessage(err, 'Failed to update your profile.');
            setError(msg);
            toast.error(msg);
        } finally {
            setSaving(false);
        }
    };

    return (
        <div className="glass-panel" style={{ padding: '28px' }}>
            {error && (
                <div style={{ marginBottom: '20px' }}>
                    <ErrorBanner>{error}</ErrorBanner>
                </div>
            )}

            <div style={{ display: 'flex', gap: '28px', alignItems: 'flex-start', flexWrap: 'wrap' }}>
                {/* Avatar column */}
                <div
                    style={{
                        display: 'flex',
                        flexDirection: 'column',
                        alignItems: 'center',
                        gap: '12px',
                    }}
                >
                    <Avatar
                        src={avatarSrc}
                        firstName={me.profile?.first_name}
                        lastName={me.profile?.last_name}
                        name={me.username}
                        size={96}
                    />
                    {/* Avatar upload is intentionally not offered: the backend exposes no
                        avatar write endpoint (UserDto.ProfilePayload.avatar is accepted but
                        ignored), so a "Change avatar" control could never succeed. */}
                    <span
                        style={{
                            fontSize: '12px',
                            color: 'var(--text-muted)',
                            textAlign: 'center',
                            maxWidth: '120px',
                        }}
                    >
                        Avatar changes are not supported yet.
                    </span>
                </div>

                {/* Form column */}
                <form onSubmit={handleSave} style={{ flex: 1, minWidth: '280px' }}>
                    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
                        <div className="form-group" style={{ marginBottom: 0 }}>
                            <label className="form-label" htmlFor="settings-first-name">
                                First name
                            </label>
                            <input
                                id="settings-first-name"
                                className="form-control"
                                value={firstName}
                                onChange={(e) => setFirstName(e.target.value)}
                                disabled={saving}
                                autoComplete="given-name"
                            />
                        </div>
                        <div className="form-group" style={{ marginBottom: 0 }}>
                            <label className="form-label" htmlFor="settings-last-name">
                                Last name
                            </label>
                            <input
                                id="settings-last-name"
                                className="form-control"
                                value={lastName}
                                onChange={(e) => setLastName(e.target.value)}
                                disabled={saving}
                                autoComplete="family-name"
                            />
                        </div>
                    </div>

                    <div className="form-group" style={{ marginTop: '16px', marginBottom: 0 }}>
                        <label className="form-label">Username</label>
                        <input className="form-control" value={me.username} readOnly disabled />
                    </div>

                    <div style={{ marginTop: '16px', display: 'flex', alignItems: 'center', gap: '10px' }}>
                        <span className="form-label" style={{ margin: 0 }}>
                            Role
                        </span>
                        <Badge variant={me.role?.name === 'admin' ? 'primary' : 'default'}>
                            {me.role?.name ?? 'user'}
                        </Badge>
                    </div>

                    <div style={{ marginTop: '24px', display: 'flex', gap: '12px' }}>
                        <button type="submit" className="btn btn-primary" disabled={saving || !dirty}>
                            {saving ? <Spinner size={16} color="#fff" /> : null}
                            {saving ? 'Saving...' : 'Save changes'}
                        </button>
                    </div>
                </form>
            </div>
        </div>
    );
}

// ===========================================================================
// Security (MFA / TOTP) tab
// ===========================================================================
type MfaStatus = 'loading' | 'disabled' | 'enabled' | 'error';

function SecurityTab() {
    const toast = useToast();

    const [status, setStatus] = useState<MfaStatus>('loading');
    const [verified, setVerified] = useState<string | null>(null);
    const [error, setError] = useState<string | null>(null);
    const [rateLimited, setRateLimited] = useState(false);

    // Setup flow state.
    const [setup, setSetup] = useState<MfaSetupState | null>(null);
    const [provisioning, setProvisioning] = useState(false);
    const [code, setCode] = useState('');
    const [enabling, setEnabling] = useState(false);

    // Disable flow state.
    const [confirmDisable, setConfirmDisable] = useState(false);
    const [disabling, setDisabling] = useState(false);

    const probe = useCallback(async () => {
        setStatus('loading');
        setError(null);
        setRateLimited(false);
        try {
            // start.json: body present (with verified) => configured; null => not configured.
            const started = await startTotpSetup();
            if (started && started.verified) {
                setVerified(started.verified ?? null);
                setStatus('enabled');
                return;
            }
            // Fall back to the fuller state which may also carry `verified`.
            const state = await getTotpSetupState();
            if (state.verified) {
                setVerified(state.verified ?? null);
                setStatus('enabled');
            } else {
                setStatus('disabled');
            }
        } catch (err: unknown) {
            if (httpStatus(err) === 429) setRateLimited(true);
            setError(errMessage(err, 'Failed to load MFA status.'));
            setStatus('error');
        }
    }, []);

    useEffect(() => {
        void probe();
    }, [probe]);

    const beginSetup = async () => {
        setProvisioning(true);
        setError(null);
        setRateLimited(false);
        try {
            const state = await getTotpSetupState();
            if (!state.otpProvisioningUri) {
                throw new Error('Server did not return a provisioning URI.');
            }
            setSetup(state);
            setCode('');
        } catch (err: unknown) {
            if (httpStatus(err) === 429) setRateLimited(true);
            setError(errMessage(err, 'Failed to start TOTP setup.'));
        } finally {
            setProvisioning(false);
        }
    };

    const cancelSetup = () => {
        setSetup(null);
        setCode('');
        setError(null);
    };

    const handleEnable = async (e: FormEvent) => {
        e.preventDefault();
        if (!setup?.otpProvisioningUri) return;
        if (!/^\d{6}$/.test(code)) {
            setError('Enter the 6-digit code from your authenticator.');
            return;
        }
        setEnabling(true);
        setError(null);
        setRateLimited(false);
        try {
            const result = await enableTotp({
                otpProvisioningUri: setup.otpProvisioningUri,
                totp: code,
            });
            setVerified(result.verified ?? new Date().toISOString());
            setSetup(null);
            setCode('');
            setStatus('enabled');
            toast.success('Two-factor authentication enabled.');
        } catch (err: unknown) {
            if (httpStatus(err) === 429) {
                setRateLimited(true);
                setError('Too many attempts. Please try again later.');
            } else {
                setError(
                    errMessage(
                        err,
                        'That code did not verify. Check your authenticator and try again.',
                    ),
                );
            }
        } finally {
            setEnabling(false);
        }
    };

    const handleDisable = async () => {
        setDisabling(true);
        setError(null);
        try {
            await disableTotp();
            setVerified(null);
            setStatus('disabled');
            setConfirmDisable(false);
            toast.success('Two-factor authentication disabled.');
        } catch (err: unknown) {
            const msg = errMessage(err, 'Failed to disable MFA.');
            setError(msg);
            toast.error(msg);
        } finally {
            setDisabling(false);
        }
    };

    const parsed = useMemo(
        () => (setup?.otpProvisioningUri ? parseOtpauth(setup.otpProvisioningUri) : null),
        [setup],
    );

    return (
        <div className="glass-panel" style={{ padding: '28px' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '8px' }}>
                <ShieldCheck size={22} color="var(--primary-color)" />
                <h2 style={{ margin: 0, fontSize: '18px' }}>Two-factor authentication (TOTP)</h2>
                {status === 'enabled' && <Badge variant="success">Enabled</Badge>}
                {status === 'disabled' && <Badge variant="muted">Not configured</Badge>}
            </div>
            <p style={{ color: 'var(--text-secondary)', marginTop: 0, marginBottom: '20px' }}>
                Add a one-time passcode from an authenticator app (Google Authenticator, Authy,
                1Password, etc.) as a second factor at login.
            </p>

            {rateLimited && (
                <div style={{ marginBottom: '16px' }}>
                    <ErrorBanner>Too many attempts, please try again later.</ErrorBanner>
                </div>
            )}
            {error && !rateLimited && (
                <div style={{ marginBottom: '16px' }}>
                    <ErrorBanner>{error}</ErrorBanner>
                </div>
            )}

            {status === 'loading' && <FullSpinner label="Checking MFA status..." />}

            {status === 'error' && (
                <button type="button" className="btn btn-secondary" onClick={() => void probe()}>
                    Retry
                </button>
            )}

            {/* ENABLED state */}
            {status === 'enabled' && (
                <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
                    <div
                        style={{
                            display: 'flex',
                            alignItems: 'center',
                            gap: '10px',
                            color: 'var(--text-secondary)',
                            fontSize: '14px',
                        }}
                    >
                        <Check size={18} color="var(--success-color)" />
                        <span>
                            Enabled
                            {verified ? <> since {formatDate(verified)}</> : null}.
                        </span>
                    </div>
                    <div>
                        <button
                            type="button"
                            className="btn btn-secondary"
                            style={{ color: 'var(--danger-color)', borderColor: 'var(--danger-color)' }}
                            onClick={() => setConfirmDisable(true)}
                        >
                            <ShieldOff size={16} /> Disable two-factor
                        </button>
                    </div>
                </div>
            )}

            {/* DISABLED state — CTA or active setup flow */}
            {status === 'disabled' && !setup && (
                <button
                    type="button"
                    className="btn btn-primary"
                    onClick={() => void beginSetup()}
                    disabled={provisioning}
                >
                    {provisioning ? <Spinner size={16} color="#fff" /> : <ShieldCheck size={16} />}
                    {provisioning ? 'Preparing...' : 'Set up two-factor'}
                </button>
            )}

            {status === 'disabled' && setup?.otpProvisioningUri && (
                <div style={{ display: 'flex', gap: '28px', flexWrap: 'wrap', alignItems: 'flex-start' }}>
                    <div
                        style={{
                            display: 'flex',
                            flexDirection: 'column',
                            alignItems: 'center',
                            gap: '8px',
                        }}
                    >
                        <OtpauthQr data={setup.otpProvisioningUri} />
                        <span style={{ fontSize: '12px', color: 'var(--text-muted)' }}>
                            Scan with your authenticator
                        </span>
                    </div>

                    <div style={{ flex: 1, minWidth: '300px' }}>
                        <p
                            style={{
                                marginTop: 0,
                                color: 'var(--text-secondary)',
                                fontSize: '14px',
                                lineHeight: 1.6,
                            }}
                        >
                            Can't scan? Open your authenticator app and add an account manually by
                            pasting either the setup key or the full <code>otpauth://</code> URI below.
                        </p>

                        {parsed?.secret && (
                            <div className="form-group">
                                <label className="form-label">Setup key (manual entry)</label>
                                <CopyChip value={parsed.secret} />
                            </div>
                        )}

                        <div className="form-group">
                            <label className="form-label">otpauth:// URI</label>
                            <CopyChip value={setup.otpProvisioningUri} />
                        </div>

                        <form onSubmit={handleEnable} style={{ marginTop: '8px' }}>
                            <div className="form-group">
                                <label className="form-label" htmlFor="totp-code">
                                    Enter the 6-digit code to confirm
                                </label>
                                <input
                                    id="totp-code"
                                    className="form-control"
                                    inputMode="numeric"
                                    autoComplete="one-time-code"
                                    maxLength={6}
                                    placeholder="000000"
                                    value={code}
                                    onChange={(e) =>
                                        setCode(e.target.value.replace(/\D/g, '').slice(0, 6))
                                    }
                                    disabled={enabling}
                                    style={{
                                        fontFamily: "'SFMono-Regular', Consolas, Menlo, monospace",
                                        letterSpacing: '0.3em',
                                        maxWidth: '180px',
                                    }}
                                    autoFocus
                                />
                            </div>
                            <div style={{ display: 'flex', gap: '12px' }}>
                                <button
                                    type="submit"
                                    className="btn btn-primary"
                                    disabled={enabling || code.length !== 6}
                                >
                                    {enabling ? <Spinner size={16} color="#fff" /> : null}
                                    {enabling ? 'Verifying...' : 'Verify & enable'}
                                </button>
                                <button
                                    type="button"
                                    className="btn btn-secondary"
                                    onClick={cancelSetup}
                                    disabled={enabling}
                                >
                                    Cancel
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            )}

            <ConfirmDialog
                open={confirmDisable}
                title="Disable two-factor authentication?"
                message="Your account will no longer require a one-time passcode at login. You can re-enable it at any time."
                confirmLabel="Disable"
                danger
                loading={disabling}
                onConfirm={() => void handleDisable()}
                onCancel={() => setConfirmDisable(false)}
            />
        </div>
    );
}

// ===========================================================================
// Account / Server tab
// ===========================================================================
function AccountTab({ me, isAdmin }: { me: User; isAdmin: boolean }) {
    const { ownFingerprint, ownPublicKeyArmored } = useKey();

    // Prefer the in-memory unlocked-key fingerprint; fall back to the server gpgkey.
    const fingerprint = ownFingerprint ?? me.gpgkey?.fingerprint ?? null;

    return (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
            {/* GPG key card */}
            <div className="glass-panel" style={{ padding: '28px' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '6px' }}>
                    <KeyRound size={20} color="var(--primary-color)" />
                    <h2 style={{ margin: 0, fontSize: '18px' }}>Your encryption key</h2>
                </div>
                <p style={{ color: 'var(--text-secondary)', marginTop: 0, marginBottom: '16px' }}>
                    This OpenPGP key decrypts and encrypts your secrets entirely in your browser. The
                    server never sees your private key or passphrase.
                </p>

                <div className="form-group" style={{ marginBottom: 0 }}>
                    <label
                        className="form-label"
                        style={{ display: 'flex', alignItems: 'center', gap: '6px' }}
                    >
                        <Fingerprint size={14} /> Fingerprint
                    </label>
                    {fingerprint ? (
                        <CopyChip value={formatFingerprint(fingerprint)} />
                    ) : (
                        <div style={{ color: 'var(--text-muted)', fontSize: '14px' }}>
                            Your key is locked — unlock your vault to view the fingerprint.
                        </div>
                    )}
                </div>

                {me.gpgkey?.key_id && (
                    <div style={{ marginTop: '14px', display: 'flex', gap: '20px', flexWrap: 'wrap' }}>
                        <div>
                            <span className="form-label" style={{ display: 'block' }}>
                                Key ID
                            </span>
                            <code style={{ color: 'var(--text-secondary)', fontSize: '13px' }}>
                                {me.gpgkey.key_id}
                            </code>
                        </div>
                        {me.gpgkey.bits != null && (
                            <div>
                                <span className="form-label" style={{ display: 'block' }}>
                                    Length
                                </span>
                                <code style={{ color: 'var(--text-secondary)', fontSize: '13px' }}>
                                    {me.gpgkey.bits} bits
                                </code>
                            </div>
                        )}
                        <div>
                            <span className="form-label" style={{ display: 'block' }}>
                                In-memory status
                            </span>
                            <Badge variant={ownPublicKeyArmored ? 'success' : 'muted'}>
                                {ownPublicKeyArmored ? 'Unlocked' : 'Locked'}
                            </Badge>
                        </div>
                    </div>
                )}

                <div
                    style={{
                        marginTop: '24px',
                        borderTop: '1px solid var(--panel-border)',
                        paddingTop: '20px',
                    }}
                >
                    <button type="button" className="btn btn-secondary" onClick={logout}>
                        <LogOut size={16} /> Log out
                    </button>
                </div>
            </div>

            {/* Server settings card */}
            <ServerSettingsCard isAdmin={isAdmin} />
        </div>
    );
}

function ServerSettingsCard({ isAdmin }: { isAdmin: boolean }) {
    const toast = useToast();
    const [settings, setSettings] = useState<ServerSettings | null>(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState<string | null>(null);

    // Org MFA (admin only).
    const [orgMfa, setOrgMfa] = useState<MfaOrgSettings | null>(null);
    const [orgMfaError, setOrgMfaError] = useState<string | null>(null);
    const [orgMfaBusy, setOrgMfaBusy] = useState(false);

    useEffect(() => {
        let cancelled = false;
        (async () => {
            setLoading(true);
            setError(null);
            try {
                const s = await getServerSettings();
                if (!cancelled) setSettings(s);
            } catch (err: unknown) {
                if (!cancelled) setError(errMessage(err, 'Failed to load server settings.'));
            } finally {
                if (!cancelled) setLoading(false);
            }
            if (isAdmin) {
                try {
                    const m = await getOrgMfaSettings();
                    if (!cancelled) setOrgMfa(m);
                } catch (err: unknown) {
                    if (!cancelled) {
                        setOrgMfaError(
                            httpStatus(err) === 403
                                ? 'You do not have permission to view organization MFA settings.'
                                : errMessage(err, 'Failed to load organization MFA settings.'),
                        );
                    }
                }
            }
        })();
        return () => {
            cancelled = true;
        };
    }, [isAdmin]);

    const rows = useMemo(() => (settings ? flattenSettings(settings) : []), [settings]);

    const totpOrgEnabled = !!orgMfa?.providers?.includes('totp');

    const toggleOrgTotp = async () => {
        if (!orgMfa) return;
        setOrgMfaBusy(true);
        setOrgMfaError(null);
        const next = totpOrgEnabled ? [] : ['totp'];
        try {
            const updated = await updateOrgMfaSettings(next);
            setOrgMfa(updated);
            toast.success(next.length ? 'Organization TOTP enabled.' : 'Organization TOTP disabled.');
        } catch (err: unknown) {
            const msg =
                httpStatus(err) === 403
                    ? 'You do not have permission to change organization MFA settings.'
                    : errMessage(err, 'Failed to update organization MFA settings.');
            setOrgMfaError(msg);
            toast.error(msg);
        } finally {
            setOrgMfaBusy(false);
        }
    };

    return (
        <div className="glass-panel" style={{ padding: '28px' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '6px' }}>
                <Server size={20} color="var(--primary-color)" />
                <h2 style={{ margin: 0, fontSize: '18px' }}>Server</h2>
            </div>
            <p style={{ color: 'var(--text-secondary)', marginTop: 0, marginBottom: '16px' }}>
                Read-only information reported by the JPassbolt API.
            </p>

            {loading ? (
                <FullSpinner label="Loading server settings..." />
            ) : error ? (
                <ErrorBanner>{error}</ErrorBanner>
            ) : rows.length === 0 ? (
                <div style={{ color: 'var(--text-muted)', fontSize: '14px' }}>
                    No server settings were returned.
                </div>
            ) : (
                <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '13px' }}>
                    <tbody>
                        {rows.map(({ key, value }) => (
                            <tr key={key} style={{ borderBottom: '1px solid var(--panel-border)' }}>
                                <td
                                    style={{
                                        padding: '8px 12px 8px 0',
                                        color: 'var(--text-secondary)',
                                        whiteSpace: 'nowrap',
                                        verticalAlign: 'top',
                                        fontFamily: "'SFMono-Regular', Consolas, Menlo, monospace",
                                    }}
                                >
                                    {key}
                                </td>
                                <td
                                    style={{
                                        padding: '8px 0',
                                        color: 'var(--text-primary)',
                                        wordBreak: 'break-word',
                                        fontFamily: "'SFMono-Regular', Consolas, Menlo, monospace",
                                    }}
                                >
                                    {value}
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            )}

            {/* Org MFA control (admin only) */}
            {isAdmin && (
                <div
                    style={{
                        marginTop: '24px',
                        borderTop: '1px solid var(--panel-border)',
                        paddingTop: '20px',
                    }}
                >
                    <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '8px' }}>
                        <ShieldCheck size={18} color="var(--primary-color)" />
                        <h3 style={{ margin: 0, fontSize: '15px' }}>Organization two-factor (admin)</h3>
                        {orgMfa && (
                            <Badge variant={totpOrgEnabled ? 'success' : 'muted'}>
                                {totpOrgEnabled ? 'TOTP enabled' : 'TOTP disabled'}
                            </Badge>
                        )}
                    </div>
                    {orgMfaError ? (
                        <ErrorBanner>{orgMfaError}</ErrorBanner>
                    ) : orgMfa ? (
                        <>
                            <p
                                style={{
                                    color: 'var(--text-secondary)',
                                    margin: '0 0 12px',
                                    fontSize: '14px',
                                    lineHeight: 1.6,
                                }}
                            >
                                {totpOrgEnabled
                                    ? 'TOTP is available to all users in this organization.'
                                    : 'TOTP is currently disabled organization-wide.'}
                            </p>
                            <button
                                type="button"
                                className={`btn ${totpOrgEnabled ? 'btn-secondary' : 'btn-primary'}`}
                                onClick={() => void toggleOrgTotp()}
                                disabled={orgMfaBusy}
                                style={
                                    totpOrgEnabled
                                        ? { color: 'var(--danger-color)', borderColor: 'var(--danger-color)' }
                                        : undefined
                                }
                            >
                                {orgMfaBusy ? <Spinner size={16} /> : null}
                                {totpOrgEnabled ? 'Disable TOTP org-wide' : 'Enable TOTP org-wide'}
                            </button>
                        </>
                    ) : (
                        <FullSpinner label="Loading organization MFA..." />
                    )}
                </div>
            )}
        </div>
    );
}

// ---------------------------------------------------------------------------
// Pure presentation helpers
// ---------------------------------------------------------------------------

/** RFC3339 / ISO string -> human readable; passes through unparsable input. */
function formatDate(value: string): string {
    const d = new Date(value);
    if (Number.isNaN(d.getTime())) return value;
    return d.toLocaleString();
}

/** Group an OpenPGP fingerprint into 4-char blocks for readability. */
function formatFingerprint(fp: string): string {
    const clean = fp.replace(/\s+/g, '').toUpperCase();
    return clean.match(/.{1,4}/g)?.join(' ') ?? clean;
}

/** Flatten a (possibly nested) ServerSettings map into displayable key/value rows. */
function flattenSettings(
    obj: Record<string, unknown>,
    prefix = '',
): { key: string; value: string }[] {
    const rows: { key: string; value: string }[] = [];
    for (const [k, v] of Object.entries(obj)) {
        const key = prefix ? `${prefix}.${k}` : k;
        if (v == null) {
            rows.push({ key, value: '—' });
        } else if (Array.isArray(v)) {
            rows.push({ key, value: v.map((x) => stringifyScalar(x)).join(', ') || '[]' });
        } else if (typeof v === 'object') {
            rows.push(...flattenSettings(v as Record<string, unknown>, key));
        } else {
            rows.push({ key, value: stringifyScalar(v) });
        }
    }
    return rows;
}

function stringifyScalar(v: unknown): string {
    if (v == null) return '—';
    if (typeof v === 'object') {
        try {
            return JSON.stringify(v);
        } catch {
            return String(v);
        }
    }
    return String(v);
}

// ===========================================================================
// Minimal QR-code encoder (byte mode, ECC level M) — no external dependency.
// Returns a boolean matrix (true = dark module). Supports QR versions 1..10,
// which comfortably hold a typical otpauth:// payload (~120 chars at level M).
// Mask pattern 0 ((row + col) % 2 === 0) is applied unconditionally.
// ===========================================================================

// Capacity (bytes) for byte mode at ECC level M, versions 1..10.
const BYTE_CAPACITY_M = [0, 14, 26, 42, 62, 84, 106, 122, 152, 180, 213];

// Error-correction structure per version (level M): EC codewords per block + block groups.
const EC_TABLE_M: Record<number, { ecPerBlock: number; groups: [number, number][] }> = {
    1: { ecPerBlock: 10, groups: [[1, 16]] },
    2: { ecPerBlock: 16, groups: [[1, 28]] },
    3: { ecPerBlock: 26, groups: [[1, 44]] },
    4: { ecPerBlock: 18, groups: [[2, 32]] },
    5: { ecPerBlock: 24, groups: [[2, 43]] },
    6: { ecPerBlock: 16, groups: [[4, 27]] },
    7: { ecPerBlock: 18, groups: [[4, 31]] },
    8: { ecPerBlock: 22, groups: [[2, 38], [2, 39]] },
    9: { ecPerBlock: 22, groups: [[3, 36], [2, 37]] },
    10: { ecPerBlock: 26, groups: [[4, 43], [1, 44]] },
};

const ALIGNMENT_CENTERS: Record<number, number[]> = {
    2: [6, 18],
    3: [6, 22],
    4: [6, 26],
    5: [6, 30],
    6: [6, 34],
    7: [6, 22, 38],
    8: [6, 24, 42],
    9: [6, 26, 46],
    10: [6, 28, 50],
};

function buildQrMatrix(text: string): boolean[][] {
    const data = new TextEncoder().encode(text);
    let version = 0;
    for (let v = 1; v <= 10; v++) {
        if (data.length <= BYTE_CAPACITY_M[v]) {
            version = v;
            break;
        }
    }
    if (version === 0) throw new Error('Payload too large for supported QR versions.');

    const size = 17 + version * 4;
    const ec = EC_TABLE_M[version];

    // --- Build the data bit-stream (mode + count + bytes + terminator + pad). ---
    const totalDataCodewords = ec.groups.reduce((sum, [n, c]) => sum + n * c, 0);
    const bits: number[] = [];
    const pushBits = (val: number, len: number) => {
        for (let i = len - 1; i >= 0; i--) bits.push((val >> i) & 1);
    };
    pushBits(0b0100, 4); // byte mode
    pushBits(data.length, version <= 9 ? 8 : 16); // char-count indicator
    for (const b of data) pushBits(b, 8);
    const capacityBits = totalDataCodewords * 8;
    const term = Math.min(4, capacityBits - bits.length);
    for (let i = 0; i < term; i++) bits.push(0);
    while (bits.length % 8 !== 0) bits.push(0);
    const padBytes = [0xec, 0x11];
    let pi = 0;
    while (bits.length < capacityBits) {
        pushBits(padBytes[pi % 2], 8);
        pi++;
    }
    const dataCodewords: number[] = [];
    for (let i = 0; i < bits.length; i += 8) {
        let byte = 0;
        for (let j = 0; j < 8; j++) byte = (byte << 1) | bits[i + j];
        dataCodewords.push(byte);
    }

    // --- Split into blocks, compute EC, then interleave. ---
    const dataBlocks: number[][] = [];
    const ecBlocks: number[][] = [];
    let offset = 0;
    for (const [numBlocks, dataPerBlock] of ec.groups) {
        for (let b = 0; b < numBlocks; b++) {
            const block = dataCodewords.slice(offset, offset + dataPerBlock);
            offset += dataPerBlock;
            dataBlocks.push(block);
            ecBlocks.push(reedSolomon(block, ec.ecPerBlock));
        }
    }
    const maxData = Math.max(...dataBlocks.map((b) => b.length));
    const finalCodewords: number[] = [];
    for (let i = 0; i < maxData; i++) {
        for (const block of dataBlocks) if (i < block.length) finalCodewords.push(block[i]);
    }
    for (let i = 0; i < ec.ecPerBlock; i++) {
        for (const block of ecBlocks) finalCodewords.push(block[i]);
    }

    // --- Lay out the matrix. ---
    const modules: (boolean | null)[][] = Array.from({ length: size }, () =>
        Array<boolean | null>(size).fill(null),
    );
    placeFunctionPatterns(modules, version, size);
    reserveFormatAreas(modules, size);

    // Place data with the zig-zag walk + mask 0.
    const finalBits: number[] = [];
    for (const cw of finalCodewords) for (let i = 7; i >= 0; i--) finalBits.push((cw >> i) & 1);

    let bitIdx = 0;
    let upward = true;
    for (let col = size - 1; col > 0; col -= 2) {
        if (col === 6) col--; // skip the vertical timing column
        for (let i = 0; i < size; i++) {
            const row = upward ? size - 1 - i : i;
            for (let c = 0; c < 2; c++) {
                const cc = col - c;
                if (modules[row][cc] !== null) continue;
                let dark = bitIdx < finalBits.length ? finalBits[bitIdx] === 1 : false;
                bitIdx++;
                if ((row + cc) % 2 === 0) dark = !dark; // mask pattern 0
                modules[row][cc] = dark;
            }
        }
        upward = !upward;
    }

    applyFormatInfo(modules, size);

    return modules.map((r) => r.map((m) => m === true));
}

function placeFinderPattern(m: (boolean | null)[][], top: number, left: number) {
    for (let r = -1; r <= 7; r++) {
        for (let c = -1; c <= 7; c++) {
            const rr = top + r;
            const cc = left + c;
            if (rr < 0 || cc < 0 || rr >= m.length || cc >= m.length) continue;
            const inRing = r >= 0 && r <= 6 && c >= 0 && c <= 6;
            const isDark =
                inRing &&
                (r === 0 || r === 6 || c === 0 || c === 6 || (r >= 2 && r <= 4 && c >= 2 && c <= 4));
            m[rr][cc] = inRing ? isDark : false; // separators are light
        }
    }
}

function placeFunctionPatterns(m: (boolean | null)[][], version: number, size: number) {
    placeFinderPattern(m, 0, 0);
    placeFinderPattern(m, 0, size - 7);
    placeFinderPattern(m, size - 7, 0);

    // Timing patterns.
    for (let i = 8; i < size - 8; i++) {
        const v = i % 2 === 0;
        if (m[6][i] === null) m[6][i] = v;
        if (m[i][6] === null) m[i][6] = v;
    }

    // Dark module.
    m[size - 8][8] = true;

    // Alignment patterns.
    if (version >= 2) {
        const centers = ALIGNMENT_CENTERS[version] ?? [];
        for (const cr of centers) {
            for (const cc of centers) {
                if (
                    (cr <= 8 && cc <= 8) ||
                    (cr <= 8 && cc >= size - 9) ||
                    (cr >= size - 9 && cc <= 8)
                ) {
                    continue; // overlaps a finder pattern
                }
                placeAlignmentPattern(m, cr, cc);
            }
        }
    }
}

function placeAlignmentPattern(m: (boolean | null)[][], cr: number, cc: number) {
    for (let r = -2; r <= 2; r++) {
        for (let c = -2; c <= 2; c++) {
            const rr = cr + r;
            const ccc = cc + c;
            if (rr < 0 || ccc < 0 || rr >= m.length || ccc >= m.length) continue;
            const ring = Math.max(Math.abs(r), Math.abs(c));
            m[rr][ccc] = ring !== 1; // dark border + centre, light ring at distance 1
        }
    }
}

function reserveFormatAreas(m: (boolean | null)[][], size: number) {
    // Reserve the 15 format-info modules so the data walk skips them.
    for (let i = 0; i <= 8; i++) {
        if (i !== 6) {
            if (m[8][i] === null) m[8][i] = false;
            if (m[i][8] === null) m[i][8] = false;
        }
    }
    for (let i = size - 8; i < size; i++) {
        if (m[8][i] === null) m[8][i] = false;
        if (m[i][8] === null) m[i][8] = false;
    }
}

function applyFormatInfo(m: (boolean | null)[][], size: number) {
    // 15-bit format string for ECC level M, mask pattern 0.
    const FORMAT_M_MASK0 = 0b101010000010010;
    const bits: number[] = [];
    for (let i = 14; i >= 0; i--) bits.push((FORMAT_M_MASK0 >> i) & 1);

    // Copy 1 — around the top-left finder.
    let idx = 0;
    for (let r = 0; r <= 8; r++) {
        if (r === 6) continue;
        m[r][8] = bits[idx++] === 1;
    }
    for (let c = 7; c >= 0; c--) {
        if (c === 6) continue;
        m[8][c] = bits[idx++] === 1;
    }

    // Copy 2 — bottom-left (vertical) + top-right (horizontal).
    idx = 0;
    for (let r = size - 1; r >= size - 7; r--) {
        m[r][8] = bits[idx++] === 1;
    }
    for (let c = size - 8; c <= size - 1; c++) {
        m[8][c] = bits[idx++] === 1;
    }
}

// --- Reed-Solomon over GF(256) for QR error-correction codewords. ---
const GF_EXP = new Uint8Array(512);
const GF_LOG = new Uint8Array(256);
(function initGalois() {
    let x = 1;
    for (let i = 0; i < 255; i++) {
        GF_EXP[i] = x;
        GF_LOG[x] = i;
        x <<= 1;
        if (x & 0x100) x ^= 0x11d;
    }
    for (let i = 255; i < 512; i++) GF_EXP[i] = GF_EXP[i - 255];
})();

function gfMul(a: number, b: number): number {
    if (a === 0 || b === 0) return 0;
    return GF_EXP[GF_LOG[a] + GF_LOG[b]];
}

function rsGeneratorPoly(degree: number): number[] {
    let poly = [1];
    for (let i = 0; i < degree; i++) {
        const next = new Array(poly.length + 1).fill(0);
        for (let j = 0; j < poly.length; j++) {
            next[j] ^= poly[j];
            next[j + 1] ^= gfMul(poly[j], GF_EXP[i]);
        }
        poly = next;
    }
    return poly;
}

function reedSolomon(data: number[], ecLen: number): number[] {
    const gen = rsGeneratorPoly(ecLen);
    const res = new Array(ecLen).fill(0);
    for (const d of data) {
        const factor = d ^ res[0];
        res.shift();
        res.push(0);
        for (let i = 0; i < gen.length; i++) {
            res[i] ^= gfMul(gen[i], factor);
        }
    }
    return res.slice(0, ecLen);
}
