/**
 * Settings — self-service account hub.
 *
 * Three sections (inline tabs styled with btn-secondary / active = btn-primary):
 *
 *   1. Profile  — large Avatar + first/last name form (PUT /users/{uuid}.json, since the
 *                 backend rejects the "me" alias on writes). Read-only username + role.
 *                 Avatar upload is intentionally omitted (no backend write endpoint exists).
 *   2. Security — TOTP MFA. On mount probes GET /mfa/setup/totp/start.json to learn
 *                 whether MFA is already configured. If not: fetch GET /mfa/setup/totp.json
 *                 to obtain the otpauth:// provisioning URI, render it as a client-side QR
 *                 (no external dependency) + a copyable secret string, then verify a 6-digit
 *                 code via POST /mfa/setup/totp.json to enable. If configured: show the
 *                 verified timestamp + a Disable control (DELETE /mfa/setup/totp.json).
 *                 Brute-force 429 surfaces a dedicated banner.
 *   3. Account  — read-only GET /settings.json key/value table + the unlocked GPG key
 *                 fingerprint (from KeyContext / localStorage) + a Logout button. Admins
 *                 also get an org-wide MFA toggle (GET/POST /mfa/settings.json).
 *
 * Every data view has loading / empty / error states. E2EE invariant: the GPG key
 * fingerprint is read from the in-memory KeyContext (never decrypted on the server).
 */
import {
    useCallback,
    useEffect,
    useMemo,
    useRef,
    useState,
    type FormEvent,
    type ReactNode,
} from 'react';
import {
    User as UserIcon,
    ShieldCheck,
    ShieldOff,
    Server,
    Copy,
    Check,
    Fingerprint,
    LogOut,
    KeyRound,
    AlertTriangle,
    Eye,
    EyeOff,
} from 'lucide-react';
import { logout } from '../auth';
import { useKey } from '../crypto/KeyContext';
import { getMe, updateOwnProfile, avatarUrl } from '../services/profile';
import {
    getTotpSetupState,
    startTotpSetup,
    enableTotp,
    disableTotp,
    getOrgMfaSettings,
    updateOrgMfaSettings,
} from '../services/mfa';
import { getServerSettings } from '../services/settings';
import type {
    MfaOrgSettings,
    MfaSetupState,
    ServerSettings,
    User,
} from '../types';
import { Avatar } from '../components/Avatar';
import { Badge } from '../components/Badge';
import { ConfirmDialog } from '../components/ConfirmDialog';
import { FullSpinner, Spinner } from '../components/Spinner';
import { useToast } from '../components/toastContext';

// ---------------------------------------------------------------------------
// Error helpers
// ---------------------------------------------------------------------------
interface ApiErrorLike {
    response?: { status?: number; data?: { header?: { message?: string } } };
    message?: string;
}

function asApiError(err: unknown): ApiErrorLike {
    return (err ?? {}) as ApiErrorLike;
}

function errMessage(err: unknown, fallback: string): string {
    const e = asApiError(err);
    return e.response?.data?.header?.message || e.message || fallback;
}

function httpStatus(err: unknown): number | undefined {
    return asApiError(err).response?.status;
}

/**
 * The TOTP setup/probe endpoints return HTTP 400 with
 * "This authentication provider is not enabled for your organization."
 * when org-level TOTP has not been turned on. Detect that case so we can
 * surface friendly guidance instead of the raw backend string.
 */
function isTotpProviderDisabled(err: unknown): boolean {
    const e = asApiError(err);
    const raw = (e.response?.data?.header?.message || e.message || '').toLowerCase();
    return raw.includes('not enabled for your organization');
}

const TOTP_ORG_DISABLED_MESSAGE =
    '两步验证尚未在组织层启用。请管理员先在「服务器与组织」标签页开启「全组织 TOTP」，再回到此处设置。';

// ---------------------------------------------------------------------------
// otpauth:// parsing
// ---------------------------------------------------------------------------

/** Pull the base32 `secret` and human-readable label out of an otpauth:// URI. */
function parseOtpauth(uri: string): {
    secret: string | null;
    issuer: string | null;
    label: string | null;
} {
    try {
        // otpauth://totp/Issuer:account?secret=...&issuer=...
        const u = new URL(uri);
        const secret = u.searchParams.get('secret');
        const issuer = u.searchParams.get('issuer');
        const label = decodeURIComponent(u.pathname.replace(/^\/+/, '')) || null;
        return { secret, issuer, label };
    } catch {
        return { secret: null, issuer: null, label: null };
    }
}

function ErrorBanner({ children }: { children: ReactNode }) {
    return (
        <div className="warnbox">
            <AlertTriangle size={18} />
            <span>{children}</span>
        </div>
    );
}

/**
 * A dependency-free QR code generated by encoding the otpauth URI into a QR
 * matrix and drawing it on a <canvas> (byte mode, error correction level M,
 * versions 1..10). Falls back to a "scan unavailable" hint if the payload is
 * too large for the supported versions.
 */
function OtpauthQr({ data, size = 196 }: { data: string; size?: number }) {
    const canvasRef = useRef<HTMLCanvasElement | null>(null);

    // Compute the matrix during render so the failure state is derived, not set
    // synchronously inside the effect (which the lint rule forbids).
    const matrix = useMemo<boolean[][] | null>(() => {
        try {
            return buildQrMatrix(data);
        } catch {
            return null;
        }
    }, [data]);

    useEffect(() => {
        const canvas = canvasRef.current;
        if (!canvas || !matrix) return;
        const ctx = canvas.getContext('2d');
        if (!ctx) return;
        const n = matrix.length;
        const quiet = 4; // quiet-zone modules
        const total = n + quiet * 2;
        const scale = Math.max(1, Math.floor(size / total));
        const px = total * scale;
        canvas.width = px;
        canvas.height = px;
        // White background so the dark-theme page doesn't break scanning.
        ctx.fillStyle = '#ffffff';
        ctx.fillRect(0, 0, px, px);
        ctx.fillStyle = '#000000';
        for (let r = 0; r < n; r++) {
            for (let c = 0; c < n; c++) {
                if (matrix[r][c]) {
                    ctx.fillRect((c + quiet) * scale, (r + quiet) * scale, scale, scale);
                }
            }
        }
    }, [matrix, size]);

    if (!matrix) {
        return (
            <div
                style={{
                    width: size,
                    height: size,
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    textAlign: 'center',
                    background: 'var(--surface-3)',
                    border: '1px dashed var(--border-strong)',
                    borderRadius: 'var(--r)',
                    color: 'var(--text-3)',
                    fontSize: '12px',
                    padding: '12px',
                }}
            >
                无法生成二维码 —— 请将下方密钥手动粘贴到你的身份验证器。
            </div>
        );
    }

    return (
        <canvas
            ref={canvasRef}
            aria-label="TOTP 绑定二维码"
        />
    );
}

// ---------------------------------------------------------------------------
// Tabs
// ---------------------------------------------------------------------------
type Tab = 'profile' | 'security' | 'account';

const TABS: { id: Tab; label: string; icon: typeof UserIcon }[] = [
    { id: 'profile', label: '账户与资料', icon: UserIcon },
    { id: 'security', label: '安全 / 两步验证', icon: ShieldCheck },
    { id: 'account', label: '服务器与组织', icon: Server },
];

// ===========================================================================
// Page
// ===========================================================================
export default function Settings() {
    const [tab, setTab] = useState<Tab>('profile');

    const [me, setMe] = useState<User | null>(null);
    const [meLoading, setMeLoading] = useState(true);
    const [meError, setMeError] = useState<string | null>(null);

    const loadMe = useCallback(async () => {
        setMeLoading(true);
        setMeError(null);
        try {
            const user = await getMe();
            setMe(user);
        } catch (err: unknown) {
            setMeError(errMessage(err, 'Failed to load your account.'));
        } finally {
            setMeLoading(false);
        }
    }, []);

    useEffect(() => {
        void loadMe();
    }, [loadMe]);

    const isAdmin = me?.role?.name === 'admin';

    return (
        <div className="page">
            <div className="slayout">
                {/* Left settings nav */}
                <div className="snav">
                    <div className="snav-label">设置</div>
                    {TABS.map(({ id, label, icon: Icon }) => (
                        <button
                            key={id}
                            type="button"
                            className={`snav-item${tab === id ? ' on' : ''}`}
                            onClick={() => setTab(id)}
                        >
                            <Icon /> {label}
                        </button>
                    ))}
                </div>

                {/* Right content */}
                <div className="scontent">
                    <div className="scontent-inner">
                        {meLoading ? (
                            <FullSpinner label="正在加载你的账户..." />
                        ) : meError ? (
                            <ErrorBanner>{meError}</ErrorBanner>
                        ) : (
                            <>
                                {tab === 'profile' && me && <ProfileTab me={me} onSaved={loadMe} />}
                                {tab === 'security' && <SecurityTab />}
                                {tab === 'account' && me && (
                                    <AccountTab me={me} isAdmin={isAdmin} />
                                )}
                            </>
                        )}
                    </div>
                </div>
            </div>
        </div>
    );
}

// ===========================================================================
// Profile tab
// ===========================================================================
function ProfileTab({ me, onSaved }: { me: User; onSaved: () => void | Promise<void> }) {
    const toast = useToast();
    const [firstName, setFirstName] = useState(me.profile?.first_name ?? '');
    const [lastName, setLastName] = useState(me.profile?.last_name ?? '');
    const [saving, setSaving] = useState(false);
    const [error, setError] = useState<string | null>(null);

    const dirty =
        firstName !== (me.profile?.first_name ?? '') || lastName !== (me.profile?.last_name ?? '');

    const avatarSrc = avatarUrl(me, 'medium');

    const handleSave = async (e: FormEvent) => {
        e.preventDefault();
        if (!firstName.trim() || !lastName.trim()) {
            setError('姓与名均为必填项。');
            return;
        }
        setSaving(true);
        setError(null);
        try {
            await updateOwnProfile({
                first_name: firstName.trim(),
                last_name: lastName.trim(),
            });
            toast.success('资料已更新。');
            await onSaved();
        } catch (err: unknown) {
            const msg = errMessage(err, '更新资料失败。');
            setError(msg);
            toast.error(msg);
        } finally {
            setSaving(false);
        }
    };

    return (
        <form onSubmit={handleSave} style={{ display: 'contents' }}>
            <h2 className="stitle">账户与资料</h2>
            <div className="ssub">管理你的身份信息、显示名称与登录凭据。</div>

            {error && (
                <div style={{ marginBottom: '18px' }}>
                    <ErrorBanner>{error}</ErrorBanner>
                </div>
            )}

            {/* Identity card */}
            <div className="scard">
                <div className="srow">
                    <Avatar
                        src={avatarSrc}
                        firstName={me.profile?.first_name}
                        lastName={me.profile?.last_name}
                        name={me.username}
                        size={56}
                    />
                    <div className="sk">
                        <div className="label">
                            {[me.profile?.first_name, me.profile?.last_name]
                                .filter(Boolean)
                                .join(' ') || me.username}
                        </div>
                        {/* Avatar upload is intentionally not offered: the backend exposes no
                            avatar write endpoint (UserDto.ProfilePayload.avatar is accepted but
                            ignored), so a "Change avatar" control could never succeed. */}
                        <div className="hint">头像更换暂未支持。</div>
                    </div>
                    <div className="sv">
                        <Badge variant={me.role?.name === 'admin' ? 'primary' : 'default'}>
                            {me.role?.name ?? 'user'}
                        </Badge>
                    </div>
                </div>

                <div className="srow">
                    <div className="sk">
                        <div className="label">名字</div>
                    </div>
                    <div className="sv">
                        <input
                            id="settings-first-name"
                            className="sinput sans"
                            value={firstName}
                            onChange={(e) => setFirstName(e.target.value)}
                            disabled={saving}
                            autoComplete="given-name"
                        />
                    </div>
                </div>

                <div className="srow">
                    <div className="sk">
                        <div className="label">姓氏</div>
                    </div>
                    <div className="sv">
                        <input
                            id="settings-last-name"
                            className="sinput sans"
                            value={lastName}
                            onChange={(e) => setLastName(e.target.value)}
                            disabled={saving}
                            autoComplete="family-name"
                        />
                    </div>
                </div>

                <div className="srow">
                    <div className="sk">
                        <div className="label">用户名</div>
                        <div className="hint">用于登录，不可更改</div>
                    </div>
                    <div className="sv">
                        <input
                            className="sinput"
                            value={me.username}
                            readOnly
                            disabled
                            style={{ color: 'var(--text-3)' }}
                        />
                    </div>
                </div>
            </div>

            <div style={{ display: 'flex', gap: '12px' }}>
                <button type="submit" className="btn primary" disabled={saving || !dirty}>
                    {saving ? <Spinner size={16} color="#fff" /> : null}
                    {saving ? '保存中...' : '保存更改'}
                </button>
            </div>
        </form>
    );
}

// ===========================================================================
// Security (MFA / TOTP) tab
// ===========================================================================
type MfaStatus = 'loading' | 'disabled' | 'enabled' | 'error';

function SecurityTab() {
    const toast = useToast();

    const [status, setStatus] = useState<MfaStatus>('loading');
    const [verified, setVerified] = useState<string | null>(null);
    const [error, setError] = useState<string | null>(null);
    const [rateLimited, setRateLimited] = useState(false);

    // Setup flow state.
    const [setup, setSetup] = useState<MfaSetupState | null>(null);
    const [provisioning, setProvisioning] = useState(false);
    const [code, setCode] = useState('');
    const [enabling, setEnabling] = useState(false);

    // Disable flow state.
    const [confirmDisable, setConfirmDisable] = useState(false);
    const [disabling, setDisabling] = useState(false);

    const probe = useCallback(async () => {
        setStatus('loading');
        setError(null);
        setRateLimited(false);
        try {
            // start.json: body present (with verified) => configured; null => not configured.
            const started = await startTotpSetup();
            if (started && started.verified) {
                setVerified(started.verified ?? null);
                setStatus('enabled');
                return;
            }
            // Fall back to the fuller state which may also carry `verified`.
            const state = await getTotpSetupState();
            if (state.verified) {
                setVerified(state.verified ?? null);
                setStatus('enabled');
            } else {
                setStatus('disabled');
            }
        } catch (err: unknown) {
            if (httpStatus(err) === 429) setRateLimited(true);
            if (isTotpProviderDisabled(err)) {
                setError(TOTP_ORG_DISABLED_MESSAGE);
            } else {
                setError(errMessage(err, '加载 MFA 状态失败。'));
            }
            setStatus('error');
        }
    }, []);

    useEffect(() => {
        void probe();
    }, [probe]);

    const beginSetup = async () => {
        setProvisioning(true);
        setError(null);
        setRateLimited(false);
        try {
            const state = await getTotpSetupState();
            if (!state.otpProvisioningUri) {
                throw new Error('服务器未返回绑定地址（provisioning URI）。');
            }
            setSetup(state);
            setCode('');
        } catch (err: unknown) {
            if (httpStatus(err) === 429) setRateLimited(true);
            if (isTotpProviderDisabled(err)) {
                setError(TOTP_ORG_DISABLED_MESSAGE);
            } else {
                setError(errMessage(err, '启动两步验证设置失败。'));
            }
        } finally {
            setProvisioning(false);
        }
    };

    const cancelSetup = () => {
        setSetup(null);
        setCode('');
        setError(null);
    };

    const handleEnable = async (e: FormEvent) => {
        e.preventDefault();
        if (!setup?.otpProvisioningUri) return;
        if (!/^\d{6}$/.test(code)) {
            setError('请输入身份验证器 App 生成的 6 位验证码。');
            return;
        }
        setEnabling(true);
        setError(null);
        setRateLimited(false);
        try {
            const result = await enableTotp({
                otpProvisioningUri: setup.otpProvisioningUri,
                totp: code,
            });
            setVerified(result.verified ?? new Date().toISOString());
            setSetup(null);
            setCode('');
            setStatus('enabled');
            toast.success('两步验证已启用。');
        } catch (err: unknown) {
            if (httpStatus(err) === 429) {
                setRateLimited(true);
                setError('尝试次数过多，请稍后再试。');
            } else {
                setError(
                    errMessage(
                        err,
                        '验证码校验未通过。请检查身份验证器 App 后重试。',
                    ),
                );
            }
        } finally {
            setEnabling(false);
        }
    };

    const handleDisable = async () => {
        setDisabling(true);
        setError(null);
        try {
            await disableTotp();
            setVerified(null);
            setStatus('disabled');
            setConfirmDisable(false);
            toast.success('两步验证已关闭。');
        } catch (err: unknown) {
            const msg = errMessage(err, '关闭 MFA 失败。');
            setError(msg);
            toast.error(msg);
        } finally {
            setDisabling(false);
        }
    };

    const parsed = useMemo(
        () => (setup?.otpProvisioningUri ? parseOtpauth(setup.otpProvisioningUri) : null),
        [setup],
    );

    return (
        <span style={{ display: 'contents' }}>
            <h2 className="stitle">安全 / 两步验证</h2>
            <div className="ssub">
                为登录链路增加一层验证。MFA 校验在服务器完成，不影响端到端加密。
            </div>

            {rateLimited && (
                <div style={{ marginBottom: '16px' }}>
                    <ErrorBanner>尝试次数过多，请稍后再试。</ErrorBanner>
                </div>
            )}
            {error && !rateLimited && (
                <div style={{ marginBottom: '16px' }}>
                    <ErrorBanner>{error}</ErrorBanner>
                </div>
            )}

            <div className="scard">
                <div className="scard-h">
                    <ShieldCheck
                        style={{ color: status === 'enabled' ? 'var(--green)' : 'var(--text-2)' }}
                    />
                    <h3>身份验证器 App (TOTP)</h3>
                    {status === 'enabled' && (
                        <span className="chip green" style={{ marginLeft: 'auto' }}>
                            <Check /> 已启用
                        </span>
                    )}
                    {status === 'disabled' && (
                        <span className="chip neutral" style={{ marginLeft: 'auto' }}>
                            未配置
                        </span>
                    )}
                </div>

                <div style={{ padding: '15px 18px' }}>
                    <div className="hint" style={{ marginBottom: '14px', lineHeight: 1.5 }}>
                        登录时使用身份验证器 App（Google Authenticator、Authy、1Password 等）生成的一次性验证码作为第二重身份验证。
                    </div>

                    {status === 'loading' && <FullSpinner label="正在检查 MFA 状态..." />}

                    {status === 'error' && (
                        <button type="button" className="btn" onClick={() => void probe()}>
                            重试
                        </button>
                    )}

                    {/* ENABLED state */}
                    {status === 'enabled' && (
                        <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
                            <div
                                style={{
                                    display: 'flex',
                                    alignItems: 'center',
                                    gap: '10px',
                                    color: 'var(--text-2)',
                                    fontSize: '13.5px',
                                }}
                            >
                                <Check size={18} color="var(--green)" />
                                <span>
                                    已启用
                                    {verified ? <>，绑定于 {formatDate(verified)}</> : null}。
                                </span>
                            </div>
                            <div>
                                <button
                                    type="button"
                                    className="btn danger"
                                    onClick={() => setConfirmDisable(true)}
                                >
                                    <ShieldOff size={16} /> 关闭两步验证
                                </button>
                            </div>
                        </div>
                    )}

                    {/* DISABLED state — CTA or active setup flow */}
                    {status === 'disabled' && !setup && (
                        <button
                            type="button"
                            className="btn primary"
                            onClick={() => void beginSetup()}
                            disabled={provisioning}
                        >
                            {provisioning ? (
                                <Spinner size={16} color="#fff" />
                            ) : (
                                <ShieldCheck size={16} />
                            )}
                            {provisioning ? '准备中...' : '设置两步验证'}
                        </button>
                    )}
                </div>

                {status === 'disabled' && setup?.otpProvisioningUri && (
                    <div className="qr-setup">
                        <div className="qr">
                            <OtpauthQr data={setup.otpProvisioningUri} />
                        </div>
                        <div className="qr-info">
                            <ol>
                                <li>
                                    用 Google Authenticator、1Password 或 Authy 扫描二维码。
                                </li>
                                {parsed?.secret && (
                                    <li>
                                        或手动输入密钥：
                                        <br />
                                        <span className="qr-secret">
                                            {parsed.secret}
                                            <CopyButton value={parsed.secret} />
                                        </span>
                                    </li>
                                )}
                                <li>
                                    或粘贴完整的 <code>otpauth://</code> URI：
                                    <br />
                                    <span className="qr-secret" style={{ maxWidth: '100%' }}>
                                        <span
                                            style={{
                                                overflow: 'hidden',
                                                textOverflow: 'ellipsis',
                                                whiteSpace: 'nowrap',
                                                maxWidth: 200,
                                            }}
                                        >
                                            {setup.otpProvisioningUri}
                                        </span>
                                        <CopyButton value={setup.otpProvisioningUri} />
                                    </span>
                                </li>
                                <li>
                                    输入 6 位验证码完成绑定。
                                    <form onSubmit={handleEnable} style={{ marginTop: '10px' }}>
                                        <input
                                            id="totp-code"
                                            className="sinput"
                                            inputMode="numeric"
                                            autoComplete="one-time-code"
                                            maxLength={6}
                                            placeholder="000000"
                                            value={code}
                                            onChange={(e) =>
                                                setCode(
                                                    e.target.value.replace(/\D/g, '').slice(0, 6),
                                                )
                                            }
                                            disabled={enabling}
                                            style={{
                                                letterSpacing: '0.3em',
                                                minWidth: 0,
                                                width: '160px',
                                            }}
                                            autoFocus
                                        />
                                        <div style={{ display: 'flex', gap: '10px', marginTop: '12px' }}>
                                            <button
                                                type="submit"
                                                className="btn primary sm"
                                                disabled={enabling || code.length !== 6}
                                            >
                                                {enabling ? (
                                                    <Spinner size={16} color="#fff" />
                                                ) : null}
                                                {enabling ? '验证中...' : '验证并启用'}
                                            </button>
                                            <button
                                                type="button"
                                                className="btn sm"
                                                onClick={cancelSetup}
                                                disabled={enabling}
                                            >
                                                取消
                                            </button>
                                        </div>
                                    </form>
                                </li>
                            </ol>
                        </div>
                    </div>
                )}
            </div>

            <ConfirmDialog
                open={confirmDisable}
                title="关闭两步验证？"
                message="关闭后登录将不再需要一次性验证码。你可以随时重新启用。"
                confirmLabel="关闭"
                danger
                loading={disabling}
                onConfirm={() => void handleDisable()}
                onCancel={() => setConfirmDisable(false)}
            />
        </span>
    );
}

// ---------------------------------------------------------------------------
// Inline copy button matching the .qr-secret design (clipboard verbatim).
// ---------------------------------------------------------------------------
function CopyButton({ value }: { value: string }) {
    const [copied, setCopied] = useState(false);
    const onCopy = async () => {
        try {
            await navigator.clipboard.writeText(value);
            setCopied(true);
            window.setTimeout(() => setCopied(false), 2000);
        } catch {
            /* clipboard unavailable */
        }
    };
    return (
        <button type="button" onClick={onCopy} aria-label="复制" title="复制">
            {copied ? <Check size={14} color="var(--green)" /> : <Copy size={14} />}
        </button>
    );
}

// ===========================================================================
// Account / Server tab
// ===========================================================================
function AccountTab({ me, isAdmin }: { me: User; isAdmin: boolean }) {
    const { ownFingerprint, ownPublicKeyArmored } = useKey();
    const [showFp, setShowFp] = useState(false);
    const [fpCopied, setFpCopied] = useState(false);

    // Prefer the in-memory unlocked-key fingerprint; fall back to the server gpgkey.
    const fingerprint = ownFingerprint ?? me.gpgkey?.fingerprint ?? null;
    const fingerprintPretty = fingerprint ? formatFingerprint(fingerprint) : null;
    const fingerprintMasked = fingerprintPretty
        ? fingerprintPretty.replace(/[0-9A-F]/g, '•')
        : null;

    const copyFingerprint = async () => {
        if (!fingerprintPretty) return;
        try {
            await navigator.clipboard.writeText(fingerprintPretty);
            setFpCopied(true);
            window.setTimeout(() => setFpCopied(false), 2000);
        } catch {
            /* clipboard unavailable */
        }
    };

    return (
        <span style={{ display: 'contents' }}>
            <h2 className="stitle">服务器与组织</h2>
            <div className="ssub">你的加密密钥指纹、服务器信息与登录凭据。</div>

            {/* GPG key card */}
            <div className="scard">
                <div className="scard-h">
                    <Fingerprint />
                    <h3>OpenPGP 密钥指纹</h3>
                    <Badge variant={ownPublicKeyArmored ? 'success' : 'muted'}>
                        {ownPublicKeyArmored ? '已解锁' : '已锁定'}
                    </Badge>
                </div>
                <div className="srow" style={{ display: 'block' }}>
                    <div className="hint" style={{ marginBottom: 10, lineHeight: 1.5 }}>
                        此 OpenPGP 密钥在你的浏览器内完成全部加解密。可向他人公开指纹以核验身份；私钥与 passphrase 永不离开本设备、服务器永不可见。
                    </div>
                    {fingerprintPretty ? (
                        <div className="fpbox">
                            <KeyRound style={{ width: 16, height: 16, color: 'var(--text-3)' }} />
                            <span className="fpv">
                                {showFp ? fingerprintPretty : fingerprintMasked}
                            </span>
                            <button
                                type="button"
                                className="copybtn"
                                onClick={() => setShowFp((s) => !s)}
                                aria-label={showFp ? '隐藏' : '显示'}
                                title={showFp ? '隐藏' : '显示'}
                            >
                                {showFp ? <EyeOff size={16} /> : <Eye size={16} />}
                            </button>
                            <button
                                type="button"
                                className={`copybtn${fpCopied ? ' ok' : ''}`}
                                onClick={() => void copyFingerprint()}
                                aria-label="复制指纹"
                                title="复制指纹"
                            >
                                {fpCopied ? <Check size={16} /> : <Copy size={16} />}
                            </button>
                        </div>
                    ) : (
                        <div style={{ color: 'var(--text-3)', fontSize: '13.5px' }}>
                            密钥已锁定 —— 请先解锁保险库以查看指纹。
                        </div>
                    )}
                </div>

                {me.gpgkey?.key_id && (
                    <>
                        <div className="srow">
                            <div className="sk">
                                <div className="label">Key ID</div>
                            </div>
                            <div
                                className="sv"
                                style={{
                                    fontFamily: 'var(--mono)',
                                    fontSize: 13,
                                    color: 'var(--text-2)',
                                }}
                            >
                                {me.gpgkey.key_id}
                            </div>
                        </div>
                        {me.gpgkey.bits != null && (
                            <div className="srow">
                                <div className="sk">
                                    <div className="label">密钥长度</div>
                                </div>
                                <div
                                    className="sv"
                                    style={{
                                        fontFamily: 'var(--mono)',
                                        fontSize: 13,
                                        color: 'var(--text-2)',
                                    }}
                                >
                                    {me.gpgkey.bits} 位
                                </div>
                            </div>
                        )}
                    </>
                )}
            </div>

            {/* Server settings card */}
            <ServerSettingsCard isAdmin={isAdmin} />

            {/* Session / logout card */}
            <div className="scard">
                <div className="srow">
                    <div className="sk">
                        <div className="label">退出登录</div>
                        <div className="hint">清除本地会话并返回登录页</div>
                    </div>
                    <div className="sv">
                        <button type="button" className="btn danger" onClick={logout}>
                            <LogOut size={16} /> 退出登录
                        </button>
                    </div>
                </div>
            </div>
        </span>
    );
}

function ServerSettingsCard({ isAdmin }: { isAdmin: boolean }) {
    const toast = useToast();
    const [settings, setSettings] = useState<ServerSettings | null>(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState<string | null>(null);

    // Org MFA (admin only).
    const [orgMfa, setOrgMfa] = useState<MfaOrgSettings | null>(null);
    const [orgMfaError, setOrgMfaError] = useState<string | null>(null);
    const [orgMfaBusy, setOrgMfaBusy] = useState(false);

    useEffect(() => {
        let cancelled = false;
        (async () => {
            setLoading(true);
            setError(null);
            try {
                const s = await getServerSettings();
                if (!cancelled) setSettings(s);
            } catch (err: unknown) {
                if (!cancelled) setError(errMessage(err, 'Failed to load server settings.'));
            } finally {
                if (!cancelled) setLoading(false);
            }
            if (isAdmin) {
                try {
                    const m = await getOrgMfaSettings();
                    if (!cancelled) setOrgMfa(m);
                } catch (err: unknown) {
                    if (!cancelled) {
                        setOrgMfaError(
                            httpStatus(err) === 403
                                ? 'You do not have permission to view organization MFA settings.'
                                : errMessage(err, 'Failed to load organization MFA settings.'),
                        );
                    }
                }
            }
        })();
        return () => {
            cancelled = true;
        };
    }, [isAdmin]);

    const rows = useMemo(() => (settings ? flattenSettings(settings) : []), [settings]);

    const totpOrgEnabled = !!orgMfa?.providers?.includes('totp');

    const toggleOrgTotp = async () => {
        if (!orgMfa) return;
        setOrgMfaBusy(true);
        setOrgMfaError(null);
        const next = totpOrgEnabled ? [] : ['totp'];
        try {
            const updated = await updateOrgMfaSettings(next);
            setOrgMfa(updated);
            toast.success(next.length ? 'Organization TOTP enabled.' : 'Organization TOTP disabled.');
        } catch (err: unknown) {
            const msg =
                httpStatus(err) === 403
                    ? 'You do not have permission to change organization MFA settings.'
                    : errMessage(err, 'Failed to update organization MFA settings.');
            setOrgMfaError(msg);
            toast.error(msg);
        } finally {
            setOrgMfaBusy(false);
        }
    };

    return (
        <div className="scard">
            <div className="scard-h">
                <Server />
                <h3>服务器信息</h3>
            </div>

            <div style={{ padding: '15px 18px' }}>
                <div className="hint" style={{ marginBottom: rows.length ? 14 : 0 }}>
                    由 JPassbolt API 返回的只读信息。
                </div>

                {loading ? (
                    <FullSpinner label="正在加载服务器信息..." />
                ) : error ? (
                    <ErrorBanner>{error}</ErrorBanner>
                ) : rows.length === 0 ? (
                    <div style={{ color: 'var(--text-3)', fontSize: '13.5px' }}>
                        服务器未返回任何配置信息。
                    </div>
                ) : (
                    <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '13px' }}>
                        <tbody>
                            {rows.map(({ key, value }) => (
                                <tr key={key} style={{ borderBottom: '1px solid var(--border)' }}>
                                    <td
                                        style={{
                                            padding: '8px 12px 8px 0',
                                            color: 'var(--text-2)',
                                            whiteSpace: 'nowrap',
                                            verticalAlign: 'top',
                                            fontFamily: 'var(--mono)',
                                        }}
                                    >
                                        {key}
                                    </td>
                                    <td
                                        style={{
                                            padding: '8px 0',
                                            color: 'var(--text)',
                                            wordBreak: 'break-word',
                                            fontFamily: 'var(--mono)',
                                        }}
                                    >
                                        {value}
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                )}
            </div>

            {/* Org MFA control (admin only) */}
            {isAdmin && (
                <>
                    <div className="scard-h" style={{ borderTop: '1px solid var(--border)' }}>
                        <ShieldCheck />
                        <h3>组织两步验证（管理员）</h3>
                        {orgMfa && (
                            <span
                                className={`chip ${totpOrgEnabled ? 'green' : 'neutral'}`}
                                style={{ marginLeft: 'auto' }}
                            >
                                {totpOrgEnabled ? 'TOTP 已开启' : 'TOTP 已关闭'}
                            </span>
                        )}
                    </div>
                    {orgMfaError ? (
                        <div style={{ padding: '15px 18px' }}>
                            <ErrorBanner>{orgMfaError}</ErrorBanner>
                        </div>
                    ) : orgMfa ? (
                        <div className="srow">
                            <div className="sk">
                                <div className="label">全组织 TOTP</div>
                                <div className="hint">
                                    {totpOrgEnabled
                                        ? '本组织内所有用户均可启用 TOTP。'
                                        : '当前已在全组织范围内关闭 TOTP。'}
                                </div>
                            </div>
                            <div className="sv">
                                <button
                                    type="button"
                                    className={`switch${totpOrgEnabled ? ' on' : ''}`}
                                    onClick={() => void toggleOrgTotp()}
                                    disabled={orgMfaBusy}
                                    aria-pressed={totpOrgEnabled}
                                    aria-label="切换全组织 TOTP"
                                />
                            </div>
                        </div>
                    ) : (
                        <div style={{ padding: '15px 18px' }}>
                            <FullSpinner label="正在加载组织 MFA..." />
                        </div>
                    )}
                </>
            )}
        </div>
    );
}

// ---------------------------------------------------------------------------
// Pure presentation helpers
// ---------------------------------------------------------------------------

/** RFC3339 / ISO string -> human readable; passes through unparsable input. */
function formatDate(value: string): string {
    const d = new Date(value);
    if (Number.isNaN(d.getTime())) return value;
    return d.toLocaleString();
}

/** Group an OpenPGP fingerprint into 4-char blocks for readability. */
function formatFingerprint(fp: string): string {
    const clean = fp.replace(/\s+/g, '').toUpperCase();
    return clean.match(/.{1,4}/g)?.join(' ') ?? clean;
}

/** Flatten a (possibly nested) ServerSettings map into displayable key/value rows. */
function flattenSettings(
    obj: Record<string, unknown>,
    prefix = '',
): { key: string; value: string }[] {
    const rows: { key: string; value: string }[] = [];
    for (const [k, v] of Object.entries(obj)) {
        const key = prefix ? `${prefix}.${k}` : k;
        if (v == null) {
            rows.push({ key, value: '—' });
        } else if (Array.isArray(v)) {
            rows.push({ key, value: v.map((x) => stringifyScalar(x)).join(', ') || '[]' });
        } else if (typeof v === 'object') {
            rows.push(...flattenSettings(v as Record<string, unknown>, key));
        } else {
            rows.push({ key, value: stringifyScalar(v) });
        }
    }
    return rows;
}

function stringifyScalar(v: unknown): string {
    if (v == null) return '—';
    if (typeof v === 'object') {
        try {
            return JSON.stringify(v);
        } catch {
            return String(v);
        }
    }
    return String(v);
}

// ===========================================================================
// Minimal QR-code encoder (byte mode, ECC level M) — no external dependency.
// Returns a boolean matrix (true = dark module). Supports QR versions 1..10,
// which comfortably hold a typical otpauth:// payload (~120 chars at level M).
// Mask pattern 0 ((row + col) % 2 === 0) is applied unconditionally.
// ===========================================================================

// Capacity (bytes) for byte mode at ECC level M, versions 1..10.
const BYTE_CAPACITY_M = [0, 14, 26, 42, 62, 84, 106, 122, 152, 180, 213];

// Error-correction structure per version (level M): EC codewords per block + block groups.
const EC_TABLE_M: Record<number, { ecPerBlock: number; groups: [number, number][] }> = {
    1: { ecPerBlock: 10, groups: [[1, 16]] },
    2: { ecPerBlock: 16, groups: [[1, 28]] },
    3: { ecPerBlock: 26, groups: [[1, 44]] },
    4: { ecPerBlock: 18, groups: [[2, 32]] },
    5: { ecPerBlock: 24, groups: [[2, 43]] },
    6: { ecPerBlock: 16, groups: [[4, 27]] },
    7: { ecPerBlock: 18, groups: [[4, 31]] },
    8: { ecPerBlock: 22, groups: [[2, 38], [2, 39]] },
    9: { ecPerBlock: 22, groups: [[3, 36], [2, 37]] },
    10: { ecPerBlock: 26, groups: [[4, 43], [1, 44]] },
};

const ALIGNMENT_CENTERS: Record<number, number[]> = {
    2: [6, 18],
    3: [6, 22],
    4: [6, 26],
    5: [6, 30],
    6: [6, 34],
    7: [6, 22, 38],
    8: [6, 24, 42],
    9: [6, 26, 46],
    10: [6, 28, 50],
};

function buildQrMatrix(text: string): boolean[][] {
    const data = new TextEncoder().encode(text);
    let version = 0;
    for (let v = 1; v <= 10; v++) {
        if (data.length <= BYTE_CAPACITY_M[v]) {
            version = v;
            break;
        }
    }
    if (version === 0) throw new Error('Payload too large for supported QR versions.');

    const size = 17 + version * 4;
    const ec = EC_TABLE_M[version];

    // --- Build the data bit-stream (mode + count + bytes + terminator + pad). ---
    const totalDataCodewords = ec.groups.reduce((sum, [n, c]) => sum + n * c, 0);
    const bits: number[] = [];
    const pushBits = (val: number, len: number) => {
        for (let i = len - 1; i >= 0; i--) bits.push((val >> i) & 1);
    };
    pushBits(0b0100, 4); // byte mode
    pushBits(data.length, version <= 9 ? 8 : 16); // char-count indicator
    for (const b of data) pushBits(b, 8);
    const capacityBits = totalDataCodewords * 8;
    const term = Math.min(4, capacityBits - bits.length);
    for (let i = 0; i < term; i++) bits.push(0);
    while (bits.length % 8 !== 0) bits.push(0);
    const padBytes = [0xec, 0x11];
    let pi = 0;
    while (bits.length < capacityBits) {
        pushBits(padBytes[pi % 2], 8);
        pi++;
    }
    const dataCodewords: number[] = [];
    for (let i = 0; i < bits.length; i += 8) {
        let byte = 0;
        for (let j = 0; j < 8; j++) byte = (byte << 1) | bits[i + j];
        dataCodewords.push(byte);
    }

    // --- Split into blocks, compute EC, then interleave. ---
    const dataBlocks: number[][] = [];
    const ecBlocks: number[][] = [];
    let offset = 0;
    for (const [numBlocks, dataPerBlock] of ec.groups) {
        for (let b = 0; b < numBlocks; b++) {
            const block = dataCodewords.slice(offset, offset + dataPerBlock);
            offset += dataPerBlock;
            dataBlocks.push(block);
            ecBlocks.push(reedSolomon(block, ec.ecPerBlock));
        }
    }
    const maxData = Math.max(...dataBlocks.map((b) => b.length));
    const finalCodewords: number[] = [];
    for (let i = 0; i < maxData; i++) {
        for (const block of dataBlocks) if (i < block.length) finalCodewords.push(block[i]);
    }
    for (let i = 0; i < ec.ecPerBlock; i++) {
        for (const block of ecBlocks) finalCodewords.push(block[i]);
    }

    // --- Lay out the matrix. ---
    const modules: (boolean | null)[][] = Array.from({ length: size }, () =>
        Array<boolean | null>(size).fill(null),
    );
    placeFunctionPatterns(modules, version, size);
    reserveFormatAreas(modules, size);

    // Place data with the zig-zag walk + mask 0.
    const finalBits: number[] = [];
    for (const cw of finalCodewords) for (let i = 7; i >= 0; i--) finalBits.push((cw >> i) & 1);

    let bitIdx = 0;
    let upward = true;
    for (let col = size - 1; col > 0; col -= 2) {
        if (col === 6) col--; // skip the vertical timing column
        for (let i = 0; i < size; i++) {
            const row = upward ? size - 1 - i : i;
            for (let c = 0; c < 2; c++) {
                const cc = col - c;
                if (modules[row][cc] !== null) continue;
                let dark = bitIdx < finalBits.length ? finalBits[bitIdx] === 1 : false;
                bitIdx++;
                if ((row + cc) % 2 === 0) dark = !dark; // mask pattern 0
                modules[row][cc] = dark;
            }
        }
        upward = !upward;
    }

    applyFormatInfo(modules, size);

    return modules.map((r) => r.map((m) => m === true));
}

function placeFinderPattern(m: (boolean | null)[][], top: number, left: number) {
    for (let r = -1; r <= 7; r++) {
        for (let c = -1; c <= 7; c++) {
            const rr = top + r;
            const cc = left + c;
            if (rr < 0 || cc < 0 || rr >= m.length || cc >= m.length) continue;
            const inRing = r >= 0 && r <= 6 && c >= 0 && c <= 6;
            const isDark =
                inRing &&
                (r === 0 || r === 6 || c === 0 || c === 6 || (r >= 2 && r <= 4 && c >= 2 && c <= 4));
            m[rr][cc] = inRing ? isDark : false; // separators are light
        }
    }
}

function placeFunctionPatterns(m: (boolean | null)[][], version: number, size: number) {
    placeFinderPattern(m, 0, 0);
    placeFinderPattern(m, 0, size - 7);
    placeFinderPattern(m, size - 7, 0);

    // Timing patterns.
    for (let i = 8; i < size - 8; i++) {
        const v = i % 2 === 0;
        if (m[6][i] === null) m[6][i] = v;
        if (m[i][6] === null) m[i][6] = v;
    }

    // Dark module.
    m[size - 8][8] = true;

    // Alignment patterns.
    if (version >= 2) {
        const centers = ALIGNMENT_CENTERS[version] ?? [];
        for (const cr of centers) {
            for (const cc of centers) {
                if (
                    (cr <= 8 && cc <= 8) ||
                    (cr <= 8 && cc >= size - 9) ||
                    (cr >= size - 9 && cc <= 8)
                ) {
                    continue; // overlaps a finder pattern
                }
                placeAlignmentPattern(m, cr, cc);
            }
        }
    }
}

function placeAlignmentPattern(m: (boolean | null)[][], cr: number, cc: number) {
    for (let r = -2; r <= 2; r++) {
        for (let c = -2; c <= 2; c++) {
            const rr = cr + r;
            const ccc = cc + c;
            if (rr < 0 || ccc < 0 || rr >= m.length || ccc >= m.length) continue;
            const ring = Math.max(Math.abs(r), Math.abs(c));
            m[rr][ccc] = ring !== 1; // dark border + centre, light ring at distance 1
        }
    }
}

function reserveFormatAreas(m: (boolean | null)[][], size: number) {
    // Reserve the 15 format-info modules so the data walk skips them.
    for (let i = 0; i <= 8; i++) {
        if (i !== 6) {
            if (m[8][i] === null) m[8][i] = false;
            if (m[i][8] === null) m[i][8] = false;
        }
    }
    for (let i = size - 8; i < size; i++) {
        if (m[8][i] === null) m[8][i] = false;
        if (m[i][8] === null) m[i][8] = false;
    }
}

function applyFormatInfo(m: (boolean | null)[][], size: number) {
    // 15-bit format string for ECC level M, mask pattern 0.
    const FORMAT_M_MASK0 = 0b101010000010010;
    const bits: number[] = [];
    for (let i = 14; i >= 0; i--) bits.push((FORMAT_M_MASK0 >> i) & 1);

    // Copy 1 — around the top-left finder.
    let idx = 0;
    for (let r = 0; r <= 8; r++) {
        if (r === 6) continue;
        m[r][8] = bits[idx++] === 1;
    }
    for (let c = 7; c >= 0; c--) {
        if (c === 6) continue;
        m[8][c] = bits[idx++] === 1;
    }

    // Copy 2 — bottom-left (vertical) + top-right (horizontal).
    idx = 0;
    for (let r = size - 1; r >= size - 7; r--) {
        m[r][8] = bits[idx++] === 1;
    }
    for (let c = size - 8; c <= size - 1; c++) {
        m[8][c] = bits[idx++] === 1;
    }
}

// --- Reed-Solomon over GF(256) for QR error-correction codewords. ---
const GF_EXP = new Uint8Array(512);
const GF_LOG = new Uint8Array(256);
(function initGalois() {
    let x = 1;
    for (let i = 0; i < 255; i++) {
        GF_EXP[i] = x;
        GF_LOG[x] = i;
        x <<= 1;
        if (x & 0x100) x ^= 0x11d;
    }
    for (let i = 255; i < 512; i++) GF_EXP[i] = GF_EXP[i - 255];
})();

function gfMul(a: number, b: number): number {
    if (a === 0 || b === 0) return 0;
    return GF_EXP[GF_LOG[a] + GF_LOG[b]];
}

function rsGeneratorPoly(degree: number): number[] {
    let poly = [1];
    for (let i = 0; i < degree; i++) {
        const next = new Array(poly.length + 1).fill(0);
        for (let j = 0; j < poly.length; j++) {
            next[j] ^= poly[j];
            next[j + 1] ^= gfMul(poly[j], GF_EXP[i]);
        }
        poly = next;
    }
    return poly;
}

function reedSolomon(data: number[], ecLen: number): number[] {
    const gen = rsGeneratorPoly(ecLen);
    const res = new Array(ecLen).fill(0);
    for (const d of data) {
        const factor = d ^ res[0];
        res.shift();
        res.push(0);
        for (let i = 0; i < gen.length; i++) {
            res[i] ^= gfMul(gen[i], factor);
        }
    }
    return res.slice(0, ecLen);
}
